fooslife/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('league/')),
    url(r'^league/', include('league.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

league/urls.py
from django.conf.urls import url

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<city_short_name>\w{0,3})/$', views.index, name='index'),
    url(r'^(?P<city_short_name>\w{0,3})/players/$', views.player_statistics, name='player_statistics'),
    url(r'^(?P<city_short_name>\w{0,3})/matches/$', views.matches, name='matches'),
    url(r'^(?P<city_short_name>\w{0,3})/match/division/(?P<division_number>\d+)/(?P<round_number>\d+)/(?P<team1_short_name>\w{2,4})_(?P<team2_short_name>\w{2,4})/$',
        views.match_detail, name='match_detail'),
]

league/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from itertools import groupby

from django.db import models
from django.db.models import Sum, Q
from django.db.models.signals import post_save


def places_upload_directory_path(instance, filename):
    return 'images/places/{0}/{1}'.format(instance.city.short_name, filename)


def teams_upload_directory_path(instance, filename):
    return 'images/teams/{0}/{1}/{2}/{3}'.format(instance.division.season.city.short_name, instance.division.season.number, instance.division.number, filename)


def teams_small_upload_directory_path(instance, filename):
    return 'images/teams/{0}/{1}/{2}/small/{3}'.format(instance.division.season.city.short_name, instance.division.season.number, instance.division.number, filename)


def player_sort(is_race_match):
    if is_race_match:
        return '-total_goal_average', \
               '-total_games_average', \
               '-total_singles_games_average', \
               '-total_scored_goals'
    else:
        return '-total_games_average', \
           '-total_singles_games_average', \
           '-total_goal_average', \
           '-total_scored_goals'


class City(models.Model):
    name = models.CharField(max_length=67)
    short_name = models.CharField(max_length=3)
    order = models.SmallIntegerField(default=0)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        db_table = 'city'
        ordering = ['order']


class Place(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=256)
    short_name = models.CharField(max_length=20, default='')
    image = models.ImageField(upload_to=places_upload_directory_path, blank=True)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        db_table = 'place'


class Season(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=45)
    number = models.DecimalField(max_digits=4, decimal_places=1)
    is_active = models.BooleanField()
    date_start = models.DateField()
    date_end = models.DateField()

    def number_for_url(self):
        return int(self.number) if self.number % 1 == 0 else self.number

    def __unicode__(self):
        return u'%s: %s' % (self.city, self.name)

    class Meta:
        db_table = 'season'
        ordering = ['city__order']


class Division(models.Model):
    season = models.ForeignKey(Season)
    name = models.CharField(max_length=45)
    number = models.PositiveSmallIntegerField()
    race_match_format = models.BooleanField(default=False)
    without_tie = models.BooleanField(default=False)

    @property
    def sorted_team_set(self):
        return self.team_set.order_by(
                '-total_match_points',
                '-total_set_points',
                '-total_goal_average'
            ) if self.race_match_format else \
                self.team_set.order_by(
                '-total_match_points',
                '-victories',
                '-total_game_points',
                '-total_goal_average'
            )

    @property
    def teams_matches(self):
        round_index = 1
        matches_by_round = []
        rounds = Match.objects.filter(team1__division_id=self.id).values('round_number').distinct().all()

        for round in rounds:
            matches = Match.objects.filter(team1__division_id=self.id).filter(round_number=round['round_number']).all()
            matches_by_team = []
            matches_by_team.append([{'display': ''}] + [{'display': x.short_name} for x in self.team_set.order_by('name').all()])
            is_race_match = self.race_match_format

            for index, team in enumerate(self.team_set.order_by('name').all()):
                matches_by_team_columns = [{'display': team.name}, ]

                for team_versus in self.team_set.order_by('name').all():
                    if team != team_versus:
                        match = next((x for x in matches if x.team1.id == team.id and x.team2.id == team_versus.id), None)
                        if match:
                            score = {'display': '%s/%s - %s/%s' % (match.team1_set1_score,
                                                                match.team2_set1_score,
                                                                match.team1_set2_score,
                                                                match.team2_set2_score) if is_race_match else
                                '%s - %s' % (match.team1_game_points, match.team2_game_points)}
                        else:
                            score = {'display': ''}
                        matches_by_team_columns.append(score)
                    else:
                        matches_by_team_columns.append({'is_blank': True})

                matches_by_team.append(matches_by_team_columns)
            matches_by_round.append({'name': '%s, %s круг' % (round_index, round_index + 1), 'table': matches_by_team})
            round_index += 2

        return matches_by_round

    @property
    def get_players(self):
        place_counter = 0
        for index, player in enumerate(TeamPlayer.objects \
            .filter(team__division_id=self.id) \
            .order_by(*player_sort(self.race_match_format))):
            place_counter += 0 if player.is_not_in_rating else 1
            yield place_counter if not player.is_not_in_rating else '', player

    def __unicode__(self):
        return u'%s %s' % (self.season, self.name)

    class Meta:
        db_table = 'division'


class Team(models.Model):
    division = models.ForeignKey(Division)
    captain = models.ForeignKey('TeamPlayer', related_name='captain_id', blank=True, null=True)
    name = models.CharField(max_length=45)
    short_name = models.CharField(max_length=4)
    image = models.ImageField(upload_to=teams_upload_directory_path, blank=True)
    image_small = models.ImageField(upload_to=teams_small_upload_directory_path, blank=True)
    played = models.PositiveSmallIntegerField(default=0, blank=True)
    victories = models.PositiveSmallIntegerField(default=0, blank=True)
    lost = models.PositiveSmallIntegerField(default=0, blank=True)
    tie = models.PositiveSmallIntegerField(default=0, blank=True)
    lost_by_penalty = models.PositiveSmallIntegerField(default=0, blank=True)
    total_match_points = models.PositiveSmallIntegerField(default=0, blank=True)
    total_set_points = models.PositiveSmallIntegerField(blank=True, null=True)
    total_game_points = models.SmallIntegerField(blank=True, null=True)
    total_goal_average = models.SmallIntegerField(default=0, blank=True)

    def get_matches(self):
        return Match.objects\
            .filter(Q(team1_id=self.id) | Q(team2_id=self.id))\
            .filter(Q(team1__division__id=self.division.id))\
            .order_by('-date')

    def lost_display(self):
        return self.lost - (self.lost_by_penalty if self.division.without_tie else 0)


    def __unicode__(self):
        return u'%s: %s' % (self.name, self.division)

    class Meta:
        db_table = 'team'


class Player(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=256, blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.last_name, self.first_name)

    class Meta:
        db_table = 'player'


class TeamPlayer(models.Model):
    team = models.ForeignKey(Team)
    player = models.ForeignKey(Player)
    total_scored_goals = models.PositiveSmallIntegerField(default=0, blank=True)
    total_conceded_goals = models.PositiveSmallIntegerField(default=0, blank=True)
    total_goal_average = models.SmallIntegerField(default=0, blank=True)
    total_games_played = models.PositiveSmallIntegerField(default=0, blank=True)
    total_games_won = models.PositiveSmallIntegerField(default=0, blank=True)
    total_games_lost = models.PositiveSmallIntegerField(default=0, blank=True)
    total_games_tied = models.PositiveSmallIntegerField(default=0, blank=True)
    total_games_average = models.SmallIntegerField(default=0, blank=True)
    total_singles_games_played = models.PositiveSmallIntegerField(default=0, blank=True)
    total_singles_games_won = models.PositiveSmallIntegerField(default=0, blank=True)
    total_singles_games_lost = models.PositiveSmallIntegerField(default=0, blank=True)
    total_singles_games_tied = models.PositiveSmallIntegerField(default=0, blank=True)
    total_singles_games_average = models.SmallIntegerField(default=0, blank=True)
    total_doubles_games_played = models.PositiveSmallIntegerField(default=0, blank=True)
    total_doubles_games_won = models.PositiveSmallIntegerField(default=0, blank=True)
    total_doubles_games_lost = models.PositiveSmallIntegerField(default=0, blank=True)
    total_doubles_games_tied = models.PositiveSmallIntegerField(default=0, blank=True)
    total_doubles_games_average = models.SmallIntegerField(default=0, blank=True)
    is_not_in_rating = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s %s' % (self.player.last_name, self.player.first_name)

    class Meta:
        db_table = 'team_player'


class Match(models.Model):
    place = models.ForeignKey(Place)
    team1 = models.ForeignKey(Team, related_name='team1_id')
    team2 = models.ForeignKey(Team, related_name='team2_id')
    date = models.DateField()
    round_number = models.PositiveSmallIntegerField(default=1)
    team1_match_points = models.PositiveSmallIntegerField(default=0, blank=True)
    team2_match_points = models.PositiveSmallIntegerField(default=0, blank=True)
    team1_game_points = models.SmallIntegerField(blank=True, null=True)
    team2_game_points = models.SmallIntegerField(blank=True, null=True)
    team1_goals_scored = models.PositiveSmallIntegerField(blank=True, null=True)
    team1_goals_conceded = models.PositiveSmallIntegerField(blank=True, null=True)

league/templates/match/list.html
{% extends "base.html" %}

{% load l10n %}

{% block content %}
<div class="header">
    <h1><span class="title__city">{{ active_season.name }} / </span>Матчи</h1>
    <div class="season-buttons">
        {% for division in active_season.division_set.all %}
        <a class="pure-button {{ forloop.first|yesno:'pure-button-primary,' }} division-link"
           id="tab-link-division-{{ division.number }}"
           onclick="openTab('division-{{ division.number }}', 'division')">{{ division.name }}</a>
        {% endfor %}
    </div>
</div>

{% for division in active_season.division_set.all %}
<div class="content division tab-content-division" id="division-{{ division.number }}" style="display: {{ forloop.first|yesno:'block,none' }}">
    {% for team in division.team_set.all %}
    <h3>{{ team.name }}</h3>
    <table class="pure-table protocol-list-table table_style_default">
        <tbody>
        {% for match in team.get_matches %}
        {% url 'league:match_detail' selected_city team.division.number match.round_number match.team1.short_name match.team2.short_name as match_url %}
        <tr>
            <td>{% localize on %} {{ match.date|date:"d E Y" }} {% endlocalize %}</td>
            <td>
                {% if not match.is_team1_forfeit and not match.is_team2_forfeit %}
                <a class="link_theme_default" href="{{ match_url }}">
                    {{ match.team1.name }} - {{ match.team2.name }}
                </a>
                {% else %}
                    {{ match.team1.name }} - {{ match.team2.name }}
                {% endif %}
            </td>
            <td>
                {% if not match.is_team1_forfeit and not match.is_team2_forfeit %}
                <a class="link_theme_default"
                   href="{{ match_url }}">
                    {% if division.race_match_format %}
                    {{ match.team1_set_score }} - {{ match.team2_set_score }}
                    {% else %}
                    {{ match.team1_game_points }} - {{ match.team2_game_points }}{% if match.penalty_score %} ({{match.penalty_score }}){% endif %}
                    {% endif %}
                </a>
                {% else %}
                    {% if division.race_match_format %}
                    {{ match.team1_set_score }} - {{ match.team2_set_score }}
                    {% else %}
                    {{ match.team1_game_points }} - {{ match.team2_game_points }}{% if match.penalty_score %} ({{match.penalty_score }}){% endif %}{% if match.is_team1_forfeit or match.is_team2_forfeit %} (техн.){% endif %}
                    {% endif %}
                {% endif %}
            </td>
            <td>{{ match.place }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endfor %}
</div>
{% endfor %}
{% endblock content %}

league/templates/match/match_detail.html
{% extends "base.html" %}

{% load static %}
{% load l10n %}

{% block menu %}
<li class="pure-menu-item menu-item-divided pure-menu-selected">
    <a href="{% url 'league:matches' selected_city %}" class="pure-menu-link">
        {{ match.team1.short_name }} - {{ match.team2.short_name }} {{ match.date|date:"d.m.Y" }}
    </a>
</li>
{% endblock menu %}

{% block content %}
<div class="match-header">
    <div class="match-header__bar">
        {% localize on %} {{ match.date|date:"d E" }}, {% endlocalize %} «{{ match.place }}»
    </div>
    <div class="match-header__info"
         style="background-image: url({% if match.place.image %} {{ match.place.image.url }} {% endif %})">
        <div class="pure-g match-header__info-content">
            <div class="match-header__team pure-u-8-24 pure-u-sm-8-24">
                {% if match.team1.image %}
                <img class="match-header__team-logo" src="{{ match.team1.image.url }}"/>
                {% else %}
                <span class="match-header__team-logo_text" style="">{{ match.team1.short_name }}</span>
                {% endif %}
            </div>
            <div class="pure-u-8-24 pure-u-sm-8-24">
                <div class="match-header__total-score">
                    {{ match.team1_game_points }}
                    <span class="match-header__score-separator">:</span> {{ match.team2_game_points }}
                </div>
                {% if match.penalty_score %}
                <div class="match-header__sets-score">
                    <span class="score">{{ match.penalty_score }}</span> <span class="text">по пенальти</span>
                </div>
                {% endif %}
            </div>
            <div class="match-header__team match-header__team_postion_right pure-u-8-24 pure-u-sm-8-24">
                {% if match.team2.image %}
                <img class="match-header__team-logo" src="{{ match.team2.image.url }}"/>
                {% else %}
                <span class="match-header__team-logo_text" style="">{{ match.team2.short_name }}</span>
                {% endif %}
            </div>
            <div class="pure-u-12-24 pure-u-sm-12-24 match-header__team-title match-header__team-title__position_left">
                {{ match.team1.name }}
            </div>
            <div class="pure-u-12-24 pure-u-sm-12-24 match-header__team-title match-header__team-title__position_right">
                {{ match.team2.name }}
            </div>
        </div>
    </div>
</div>

<div class="content content-match">
    <div class="pure-g">
        {% for game in match.games %}
        {% if forloop.counter == 1 %}
        <div class="pure-u-24-24 pure-u-sm-12-24 set-column_position_first">
            {% endif %}
            {% if forloop.counter == 4 %}
        </div>
        <div class="pure-u-24-24 pure-u-sm-12-24 set-column_position_second">
            {% endif %}
            <table class="set-card">
                <tr>
                    <td class="set-card__counter" rowspan="2">{{ game.game_type }}</td>
                    <td class="set-card__team">
                        <span class="set-card__team-text">{{ match.team1.short_name }}</span>
                        <span class="set-card__team-img"
                              style="background-image: url({% if match.team1.image %} {{ match.team1.image.url }} {% endif %})">
                              {% if not match.team1.image %} {{ match.team1.short_name }} {% endif %}
                        </span>
                    </td>
                    <td class="set-card__player">{{ game.team1.player1 }}{% if game.team1.player2 %}<br>{{ game.team1.player2 }}{% endif %}
                    </td>
                    {% for score in game.team1.score %}
                    <td class="set-card__points {{ score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ score.balls }}
                    </td>
                    {% endfor %}
                </tr>
                <tr>
                    <td class="set-card__team">
                        <span class="set-card__team-text">{{ match.team2.short_name }}</span>
                        <span class="set-card__team-img"
                              style="background-image: url({% if match.team2.image %} {{ match.team2.image.url }} {% endif %})">
                              {% if not match.team2.image %} {{ match.team2.short_name }} {% endif %}
                          </span>
                    </td>
                    <td class="set-card__player">{{ game.team2.player1 }}{% if game.team2.player2 %}<br>{{ game.team2.player2 }}{% endif %}
                    </td>
                    {% for score in game.team2.score %}
                    <td class="set-card__points {{ score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ score.balls }}
                    </td>
                    {% endfor %}
                </tr>
            </table>
            {% if forloop.counter == 7 %}
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% if match.penalty_set.all %}
<h3 class="penalti-title">Пенальти ({{ match.penalty_score }})</h3>
<div class="pure-g">
    <div class="pure-u-24-24 pure-u-sm-12-24 penalti-table-wrapper">
        <table class="penalti-table">
            {% for penalty in match.penalty_set.all %}
            <tr>
                <td class="penalti-table__counter">{{ forloop.counter }}</td>
                <td class="penalti-table__player">{{ penalty.team1_player }}</td>
                <td class="penalti-table__points {{ penalty.is_team1_scored|yesno:'penalti-table__points_winner_yes,' }} ">
                    {% if penalty.is_team1_scored %}1{% else %}0{% endif %}
                </td>
                <td class="penalti-table__points {{ penalty.is_team2_scored|yesno:'penalti-table__points_winner_yes,' }}">{% if penalty.is_team2_scored %}1{% else %}0{% endif %}</td>
                <td class="penalti-table__player">{{ penalty.team2_player }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endif %}
</div>
{% endblock content %}

league/templates/match/race_match_detail.html
{% extends "base.html" %}

{% load static %}
{% load l10n %}
{% load league_extras %}

{% block menu %}
<li class="pure-menu-item menu-item-divided pure-menu-selected">
    <a href="{% url 'league:matches' selected_city %}" class="pure-menu-link">
        {{ match.team1.short_name }} - {{ match.team2.short_name }} {{ match.date|date:"d.m.Y" }}
    </a>
</li>
{% endblock menu %}

{% block content %}
{% race_match_games_by_set match 1 as games_set_1 %}
{% race_match_games_by_set match 2 as games_set_2 %}
<div class="match-header">
    <div class="match-header__bar">
        {% localize on %} {{ match.date|date:"d E" }}, {% endlocalize %} «{{ match.place }}»
    </div>
    <div class="match-header__info"
         style="background-image: url({% if match.place.image %} {{ match.place.image.url }} {% endif %})">
        <div class="pure-g match-header__info-content">
            <div class="match-header__team pure-u-8-24 pure-u-sm-8-24">
                {% if match.team1.image %}
                <img class="match-header__team-logo" src="{{ match.team1.image.url }}"/>
                {% else %}
                <span class="match-header__team-logo_text" style="">{{ match.team1.short_name }}</span>
                {% endif %}
            </div>
            <div class="pure-u-8-24 pure-u-sm-8-24">
                <div class="match-header__total-score">
                    {{ match.team1_set_score }}
                    <span class="match-header__score-separator">:</span> {{ match.team2_set_score }}
                </div>
                <div class="match-header__sets-score">
                    {{ match.sets_score_display }}
                </div>
            </div>
            <div class="match-header__team match-header__team_postion_right pure-u-8-24 pure-u-sm-8-24">
                {% if match.team2.image %}
                <img class="match-header__team-logo" src="{{ match.team2.image.url }}"/>
                {% else %}
                <span class="match-header__team-logo_text" style="">{{ match.team2.short_name }}</span>
                {% endif %}
            </div>
            <div class="pure-u-12-24 pure-u-sm-12-24 match-header__team-title match-header__team-title__position_left">
                {{ match.team1.name }}
            </div>
            <div class="pure-u-12-24 pure-u-sm-12-24 match-header__team-title match-header__team-title__position_right">
                {{ match.team2.name }}
            </div>
        </div>
    </div>
</div>

<div class="content content-match">
    <div class="pure-g">
        <div class="pure-u-24-24 pure-u-sm-12-24 set-column_position_first">
            <h2 class="set-title">1-ый Сет</h2>
            {% for game in games_set_1 %}
            <table class="set-card">
                <tr>
                    <td class="set-card__counter">{{ game.game_type }}</td>
                    <td>
                        <div class="set-card_score-container_division_1">
                            <div class="set-card__player">
                                {{ game.team1.player1.player.last_name }}
                                <span class="player-first-name">{{ game.team1.player1.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team1.player1.player.first_name.0 }}.</span>
                                {% if game.team1.player2 %}<br>
                                {{ game.team1.player2.player.last_name }}
                                <span class="player-first-name">{{ game.team1.player2.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team1.player2.player.first_name.0 }}.</span>
                                {% endif %}
                            </div>
                            <div class="set-card__points {{ game.team1.score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ game.team1.score.balls }}</div>
                            <div class="set-card__points {{ game.team2.score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ game.team2.score.balls }}</div>
                            <div class="set-card__player">
                                {{ game.team2.player1.player.last_name }}
                                <span class="player-first-name">{{ game.team2.player1.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team2.player1.player.first_name.0 }}.</span>
                                {% if game.team2.player2 %}<br>
                                {{ game.team2.player2.player.last_name }}
                                <span class="player-first-name">{{ game.team2.player2.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team2.player2.player.first_name.0 }}.</span>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
            {% endfor %}
        </div>
        <div class="pure-u-24-24  pure-u-sm-12-24 set-column_position_second">
            <h2 class="set-title">2-ой Сет</h2>
            {% for game in games_set_2 %}
            <table class="set-card">
                <tr>
                    <td class="set-card__counter">{{ game.game_type }}</td>
                    <td>
                        <div class="set-card_score-container_division_1">
                            <div class="set-card__player">
                                {{ game.team1.player1.player.last_name }}
                                <span class="player-first-name">{{ game.team1.player1.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team1.player1.player.first_name.0 }}.</span>
                                {% if game.team1.player2 %}<br>
                                {{ game.team1.player2.player.last_name }}
                                <span class="player-first-name">{{ game.team1.player2.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team1.player2.player.first_name.0 }}.</span>
                                {% endif %}
                            </div>
                            <div class="set-card__points {{ game.team1.score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ game.team1.score.balls }}</div>
                            <div class="set-card__points {{ game.team2.score.is_win|yesno:'set-card__points_winner_yes,' }}">{{ game.team2.score.balls }}</div>
                            <div class="set-card__player">
                                {{ game.team2.player1.player.last_name }}
                                <span class="player-first-name">{{ game.team2.player1.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team2.player1.player.first_name.0 }}.</span>
                                {% if game.team2.player2 %}<br>
                                {{ game.team2.player2.player.last_name }}
                                <span class="player-first-name">{{ game.team2.player2.player.first_name }}</span>
                                <span class="player-first-name-letter">{{ game.team2.player2.player.first_name.0 }}.</span>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}