fooslife/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('league/')),
    url(r'^league/', include('league.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

league/urls.py
from django.conf.urls import url

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<city_short_name>\w{0,3})/$', views.index, name='index'),
    url(r'^(?P<city_short_name>\w{0,3})/players/$', views.player_statistics, name='player_statistics'),
    url(r'^(?P<city_short_name>\w{0,3})/matches/$', views.matches, name='matches'),
    url(r'^(?P<city_short_name>\w{0,3})/match/division/(?P<division_number>\d+)/(?P<round_number>\d+)/(?P<team1_short_name>\w{2,4})_(?P<team2_short_name>\w{2,4})/$',
        views.match_detail, name='match_detail'),
]

league/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, get_list_or_404, render
from .models import Season, Match, Team


def index(request, city_short_name=''):
    active_season = get_list_or_404(Season,
                                     Q(city__short_name__iexact=city_short_name) if city_short_name else Q(),
                                     is_active=True)[0]

    return render(request,
                  'start_page/index.html',
                  {
                      'active_season': active_season,
                      'selected_city': city_short_name if city_short_name else active_season.city.short_name
                   })


def player_statistics(request, city_short_name):
    active_season = get_object_or_404(Season,
                                     Q(city__short_name__iexact=city_short_name) if city_short_name else Q(),
                                     is_active=True)

    return render(request,
                  'player_statistics/list.html',
                  {
                      'active_season': active_season,
                      'selected_city': city_short_name if city_short_name else active_season.city.short_name
                  })


def matches(request, city_short_name):
    active_season = get_object_or_404(Season,
                                      Q(city__short_name__iexact=city_short_name) if city_short_name else Q(),
                                      is_active=True)

    return render(request,
                  'match/list.html',
                  {
                      'active_season': active_season,
                      'selected_city': city_short_name if city_short_name else active_season.city.short_name
                  })

def match_detail(request, city_short_name, division_number, round_number, team1_short_name, team2_short_name):
    active_season = get_object_or_404(Season,
                                      Q(city__short_name__iexact=city_short_name) if city_short_name else Q(),
                                      is_active=True)
    match = get_object_or_404(Match,
                              team1__division__season__city__short_name__iexact=city_short_name,
                              team1__division__season__number=active_season.number,
                              team1__division__number=division_number,
                              round_number=round_number,
                              team1__short_name__iexact=team1_short_name,
                              team2__short_name__iexact=team2_short_name)

    if match.is_team1_forfeit or match.is_team2_forfeit:
        raise Http404()

    is_race_match = match.team1.division.race_match_format

    games = match.game_set.all()

    team1_set1_scores = {}
    team2_set1_scores = {}
    team1_set2_scores = {}
    team2_set2_scores = {}
    team_1_set1_sum = 0
    team_2_set1_sum = 0
    team_1_set2_sum = 0
    team_2_set2_sum = 0

    if is_race_match:
        for set1_games in games.filter(set=1).order_by('order'):
            team_1_set1_sum += set1_games.team1_score
            team_2_set1_sum += set1_games.team2_score

            team1_set1_scores[team_1_set1_sum] =\
                (team1_set1_scores[team_1_set1_sum] + ', ' if team1_set1_scores.has_key(team_1_set1_sum) else '') \
                + set1_games.game_type.name

            team2_set1_scores[team_2_set1_sum] = \
                (team2_set1_scores[team_2_set1_sum] + ', ' if team2_set1_scores.has_key(team_2_set1_sum) else '') \
                + set1_games.game_type.name

        for set2_games in games.filter(set=2).order_by('order'):
            team_1_set2_sum += set2_games.team1_score
            team_2_set2_sum += set2_games.team2_score

            team1_set2_scores[team_1_set2_sum] =\
                (team1_set2_scores[team_1_set2_sum] + ', ' if team1_set2_scores.has_key(team_1_set2_sum) else '') \
                + set2_games.game_type.name

            team2_set2_scores[team_2_set2_sum] = \
                (team2_set2_scores[team_2_set2_sum] + ', ' if team2_set2_scores.has_key(team_2_set2_sum) else '') \
                + set2_games.game_type.name

        teams_scores = {
            'team1_set1_scores': team1_set1_scores,
            'team2_set1_scores': team2_set1_scores,
            'team1_set2_scores': team1_set2_scores,
            'team2_set2_scores': team2_set2_scores
        }

        teams_info = {
            'team1_set1_S1': games.filter(game_type__name__iexact='S1', set=1).first().team1_player1,
            'team2_set1_S1': games.filter(game_type__name__iexact='S1', set=1).first().team2_player1,
            'team1_set2_S1': games.filter(game_type__name__iexact='S1', set=2).first().team1_player1,
            'team2_set2_S1': games.filter(game_type__name__iexact='S1', set=2).first().team2_player1,

            'team1_set1_S2': games.filter(game_type__name__iexact='S2', set=1).first().team1_player1,
            'team2_set1_S2': games.filter(game_type__name__iexact='S2', set=1).first().team2_player1,
            'team1_set2_S2': games.filter(game_type__name__iexact='S2', set=2).first().team1_player1,
            'team2_set2_S2': games.filter(game_type__name__iexact='S2', set=2).first().team2_player1,

            'team1_set1_D1_player1': games.filter(game_type__name__iexact='D1', set=1).first().team1_player1,
            'team1_set1_D1_player2': games.filter(game_type__name__iexact='D1', set=1).first().team1_player2,
            'team2_set1_D1_player1': games.filter(game_type__name__iexact='D1', set=1).first().team2_player1,
            'team2_set1_D1_player2': games.filter(game_type__name__iexact='D1', set=1).first().team2_player2,

            'team1_set2_D1_player1': games.filter(game_type__name__iexact='D1', set=2).first().team1_player1,
            'team1_set2_D1_player2': games.filter(game_type__name__iexact='D1', set=2).first().team1_player2,
            'team2_set2_D1_player1': games.filter(game_type__name__iexact='D1', set=2).first().team2_player1,
            'team2_set2_D1_player2': games.filter(game_type__name__iexact='D1', set=2).first().team2_player2,

            'team1_set1_D2_player1': games.filter(game_type__name__iexact='D2', set=1).first().team1_player1,
            'team1_set1_D2_player2': games.filter(game_type__name__iexact='D2', set=1).first().team1_player2,
            'team2_set1_D2_player1': games.filter(game_type__name__iexact='D2', set=1).first().team2_player1,
            'team2_set1_D2_player2': games.filter(game_type__name__iexact='D2', set=1).first().team2_player2,

            'team1_set2_D2_player1': games.filter(game_type__name__iexact='D2', set=2).first().team1_player1,
            'team1_set2_D2_player2': games.filter(game_type__name__iexact='D2', set=2).first().team1_player2,
            'team2_set2_D2_player1': games.filter(game_type__name__iexact='D2', set=2).first().team2_player1,
            'team2_set2_D2_player2': games.filter(game_type__name__iexact='D2', set=2).first().team2_player2,
        }
    else:
        teams_info = {}
        teams_scores = {}

    template_name = 'race_match_detail' if is_race_match else 'match_detail'

    return render(request, 'match/%s.html' % template_name, {
        'selected_city': city_short_name if city_short_name else active_season.city.short_name,
        'match': match,
        'teams_info': teams_info,
        'teams_scores': teams_scores})

league/templates/base.html
<!DOCTYPE html>

{% load static %}
{% load league_extras %}

{% url 'league:index' selected_city as home %}
{% url 'league:player_statistics' selected_city as players_statistics %}
{% url 'league:matches' selected_city as matches %}
{% random_int 1 10000 as random_v %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Командная Лига по настольному футболу">
    <meta name="og:description" content="Командная Лига по настольному футболу">
    <meta name="og:image" content="http://foos.pro/wp-content/ata-images/logo.png">
    <title>Настольный футбол: командная лига</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800,900&amp;subset=cyrillic&amp;v={{ random_v }}"
          rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css?v={{ random_v }}" integrity="sha384-"
          crossorigin="anonymous">
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="{% static 'league/css/layouts/side-menu-old-ie.css' %}?v={{ random_v }}">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css?v={{ random_v }}">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="{% static 'league/css/layouts/side-menu.css' %}?v={{ random_v }}">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css?v={{ random_v }}">
    <!--<![endif]-->
    <link rel="stylesheet" href="{% static 'league/css/protocol.css' %}?v={{ random_v }}">
</head>

<body>
<div id="layout">
    <!-- Menu toggle -->
    <div class="moble-head">
        <a id="menuLink" href="#menu" class="menu-link moble-head__menu-link">
            <!-- Hamburger icon -->
            <span></span>
        </a>
        <span class="mobile-head__logo">FOOS LEAGUE</span>
        <div class="moble-head__select-city">
            {% cities_menu selected_city %}
        </div>
    </div>

    <div id="menu">
        <div class="pure-menu">
            <div class="pure-menu-heading">
                <span class="logo">FOOS LEAGUE</span>
                <div class="pure-menu-heading__select-city">
                    {% cities_menu selected_city %}
                </div>
            </div>
            <ul class="pure-menu-list">
                <li class="pure-menu-item {% selected_menu request home %}">
                    <a href="{% url 'league:index' selected_city %}" class="pure-menu-link">Рейтинг команд</a>
                </li>
                <li class="pure-menu-item {% selected_menu request players_statistics %}">
                    <a href="{% url 'league:player_statistics' selected_city %}"
                       class="pure-menu-link">Рейтинг игроков</a>
                </li>
                <li class="pure-menu-item {% selected_menu request matches %}">
                    <a href="{% url 'league:matches' selected_city %}" class="pure-menu-link">Матчи</a>
                </li>
                {% block menu %}{% endblock menu %}
            </ul>
        </div>
    </div>

    <div id="main">
        {% block content %}{% endblock content %}
    </div>
</div>
<script src="{% static 'league/js/ui.js' %}?v={{ random_v }}"></script>
</body>

</html>